Styling
haftamudesta/BookStore pull request #5
Opened 2023-03-16 18:46 UTC by haftamudesta

this project is styling part of the Bookstore. Bookstore is a simple website that displays a list of books and allows you to:

[ ] Display a list of books
[ ] Add a book
[ ] Remove a selected book

2023-03-16 19:19 UTC, BertrandConxy requested changes
Hi @haftamudesta, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 


## Highlights 💪 
- No linter errors
- correct flow is used
- good PR


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 19:19 UTC, BertrandConxy commented on src/components/navbar.jsx
> +      </nav>
- [ ] Good job so far 👏 Please add some space on the right side of the nav bar as well as on the bookList component as on the design given 

Your design
![image](https://user-images.githubusercontent.com/90222110/225726004-565f1c83-4b37-4b9a-b08f-188c6a3719ee.png)

Design given
![image](https://user-images.githubusercontent.com/90222110/225726370-27655bf0-e52d-4ff4-a645-4321bc538e07.png)

2023-03-16 19:19 UTC, BertrandConxy commented on src/components/Book.jsx
> +  );
- [ ] Please work out the font typefaces difference that is in this part of the Book component. The book category should have the same as the buttons below it. Also the should be aligned  on same margin 

your design
![image](https://user-images.githubusercontent.com/90222110/225727385-d0c680b4-7e38-497e-b5d7-246a0ff38bf0.png)

Given design
![image](https://user-images.githubusercontent.com/90222110/225727544-6c3e1157-8cb1-4852-aeb5-2638200cfb34.png)

2023-03-16 19:19 UTC, BertrandConxy commented on src/components/Book.jsx
> +    </li>
- [ ] There are some components that make up the Book component UI that you have not included even if they should be hard coded. Check out the comparison below 

Given design
![image](https://user-images.githubusercontent.com/90222110/225729403-b6652568-3c2e-4594-81e2-5f6f4cd51ec3.png)

Your design
![image](https://user-images.githubusercontent.com/90222110/225729537-25ce7849-ca38-4445-b9b7-1fa40b522c51.png)

2023-03-16 19:19 UTC, BertrandConxy commented on src/components/form.jsx
> +        <input type="submit" value="Submit" className={classes.submit__btn} />
- [ ] Also, please work on this button in order to match the one given on the design. In terms of styles and alignment with neighboring elements. Please consider the comparison below 👇 

Your design
![image](https://user-images.githubusercontent.com/90222110/225730029-c0f526bd-6f6e-4eef-b5d0-092806bd61a0.png)

Given design
![image](https://user-images.githubusercontent.com/90222110/225730153-2f2d390e-f232-4326-b6cf-acc9142679f5.png)

2023-03-16 23:23 UTC, andersonlebon requested changes
## Hi @haftamudesta 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 23:23 UTC, andersonlebon commented on src/components/Book.jsx
> +        </li>
![image](https://user-images.githubusercontent.com/65068771/225773111-4482fdd6-d86c-44a6-af61-f2d9cc77f308.png)

- [ ] Kindly note that you need to use the same font-family as in the design template just like the previous reviewer pointed out

2023-03-16 23:23 UTC, andersonlebon commented on src/components/Book.jsx
> +        </button>
- [ ] Kindly note that this button should look like the button in the template 
Template button
![image](https://user-images.githubusercontent.com/65068771/225773481-4d88c336-81ff-443c-ac6d-3a46d01e455a.png)
Yout button
![image](https://user-images.githubusercontent.com/65068771/225773555-ceaafc47-6fa1-462d-a880-eaac4324a746.png)

Apply the same styling for you submit button
 
![image](https://user-images.githubusercontent.com/65068771/225773879-b637a82f-eff8-437f-a973-dc071b6318a5.png)

2023-03-17 07:40 UTC, peterrobert approved these changes
Hi @haftamudesta, 


### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 14:44 UTC, vickymarz approved these changes
Hi @haftamudesta, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 14:44 UTC, vickymarz approved these changes
Hi @haftamudesta, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-11 13:12 UTC, merged